name: paw_finder
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc:
  equatable:
  http:
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - img/dog1.jpg
    - img/dog2.jpg
    - img/dog3.jpg
    - img/animais1.png
    - img/animais2.png
    - img/animais3.png
    - img/banner.png